from __future__ import annotations

from dataclasses import dataclass

import torch
from deepwave import scalar
from torch import nn

from .gpr import GPRSurveyConfig, build_geometry, default_device, model_to_velocity


def _config_from_tensor(values: torch.Tensor | None) -> GPRSurveyConfig:
    if values is None:
        raise ValueError("sample_config is required. RTM parameters must come from each sample's meta.json.")
    flat = values.detach().cpu().flatten().tolist()
    if len(flat) < 11:
        raise ValueError(f"Expected 11 RTM config values, got {len(flat)}")
    return GPRSurveyConfig(
        dx=float(flat[0]),
        dz=float(flat[1]),
        dt=float(flat[2]),
        freq=float(flat[3]),
        src_x_start=float(flat[4]),
        src_x_step=float(flat[5]),
        src_z=float(flat[6]),
        rec_offset_x=float(flat[7]),
        rec_z=float(flat[8]),
        pml_width=int(round(float(flat[9]))),
        accuracy=int(round(float(flat[10]))),
        scale=1e6,
        model_kind="permittivity",
        bscan_layout="trace_by_time",
    )


@dataclass
class ImagingResult:
    direct_wave: torch.Tensor
    observed_scattered: torch.Tensor
    rtm_image: torch.Tensor


def estimate_direct_wave_batched(
    velocity: torch.Tensor,
    source_amplitudes: torch.Tensor,
    source_locations: torch.Tensor,
    receiver_locations: torch.Tensor,
    config: GPRSurveyConfig,
    shot_batch_size: int,
) -> torch.Tensor:
    outputs = []
    n_shots = source_amplitudes.shape[0]
    for start in range(0, n_shots, shot_batch_size):
        end = min(start + shot_batch_size, n_shots)
        out = scalar(
            velocity,
            [config.dz, config.dx],
            dt=config.dt,
            source_amplitudes=source_amplitudes[start:end],
            source_locations=source_locations[start:end],
            receiver_locations=receiver_locations[start:end],
            pml_width=[config.pml_width] * 4,
            pml_freq=config.freq,
            accuracy=config.accuracy,
        )
        outputs.append(out[-1])
    return torch.cat(outputs, dim=0)


def compute_rtm_illumination_compensated_batched(
    velocity: torch.Tensor,
    observed_scattered: torch.Tensor,
    source_amplitudes: torch.Tensor,
    source_locations: torch.Tensor,
    receiver_locations: torch.Tensor,
    config: GPRSurveyConfig,
    shot_batch_size: int,
    illumination_floor_fraction: float = 0.05,
    illumination_quantile: float = 0.95,
) -> torch.Tensor:
    """Return cross-correlation RTM divided by source illumination.

    The image is computed as ``sum_t S(x,z,t) R(x,z,t)`` where ``S`` is the
    source wavefield and ``R`` is the adjoint receiver wavefield generated by
    backpropagating the observed scattered/processed data. The division by
    ``sum_t S(x,z,t)^2`` compensates for near-source illumination.
    """
    image = torch.zeros_like(velocity)
    illumination = torch.zeros_like(velocity)
    n_shots = source_amplitudes.shape[0]

    with torch.enable_grad():
        for start in range(0, n_shots, shot_batch_size):
            end = min(start + shot_batch_size, n_shots)
            source_wavefields = torch.empty(
                (int(observed_scattered.shape[-1]), end - start, *velocity.shape[-2:]),
                device=velocity.device,
                dtype=velocity.dtype,
            )
            velocity_batch = velocity.detach().clone().requires_grad_(True)

            def forward_callback(state) -> None:
                source = state.get_wavefield("wavefield_0", "inner").detach()
                source_wavefields[state.step].copy_(source)
                illumination.add_((source * source).sum(dim=0))

            def backward_callback(state) -> None:
                source = source_wavefields[state.step]
                receiver = state.get_wavefield("wavefield_0", "inner").detach()
                image.add_((source * receiver).sum(dim=0))

            out = scalar(
                velocity_batch,
                [config.dz, config.dx],
                dt=config.dt,
                source_amplitudes=source_amplitudes[start:end],
                source_locations=source_locations[start:end],
                receiver_locations=receiver_locations[start:end],
                pml_width=[config.pml_width] * 4,
                pml_freq=config.freq,
                accuracy=config.accuracy,
                forward_callback=forward_callback,
                backward_callback=backward_callback,
                callback_frequency=1,
                storage_mode="device",
            )
            adjoint_source = (out[-1] * observed_scattered[start:end]).sum()
            adjoint_source.backward()
            del source_wavefields, out, velocity_batch
            if image.device.type == "cuda":
                torch.cuda.empty_cache()

    floor = torch.quantile(illumination.detach().flatten(), float(illumination_quantile))
    floor = floor.clamp_min(1e-20) * float(illumination_floor_fraction)
    return image / (illumination + floor)


class DeepwaveClosedLoopRTM(nn.Module):
    def __init__(
        self,
        shot_batch_size: int = 105,
        illumination_floor_fraction: float = 0.05,
        illumination_quantile: float = 0.95,
        device: torch.device | None = None,
    ) -> None:
        super().__init__()
        self.shot_batch_size = shot_batch_size
        self.illumination_floor_fraction = float(illumination_floor_fraction)
        self.illumination_quantile = float(illumination_quantile)
        self.device = device or default_device()

    def _ensure_single_sample(
        self,
        observed_data: torch.Tensor,
        current_model: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        if observed_data.ndim == 4 and observed_data.shape[0] == 1:
            observed_data = observed_data.squeeze(0)
        if current_model.ndim == 3 and current_model.shape[0] == 1:
            current_model = current_model.squeeze(0)
        return observed_data.to(self.device), current_model.to(self.device)

    def _build_geometry(
        self,
        n_shots: int,
        nt: int,
        nx: int,
        nz: int,
        config: GPRSurveyConfig,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        return build_geometry(
            n_shots=n_shots,
            nt=nt,
            nx=nx,
            nz=nz,
            config=config,
            device=self.device,
        )

    def synthesize_data(
        self,
        model: torch.Tensor,
        n_shots: int | None = None,
        nt: int | None = None,
        sample_config: torch.Tensor | None = None,
    ) -> torch.Tensor:
        if model.ndim == 4:
            outputs = []
            for batch_index in range(model.shape[0]):
                config_values = sample_config[batch_index] if sample_config is not None and sample_config.ndim > 1 else sample_config
                synth = self.synthesize_data(
                    model[batch_index],
                    n_shots=n_shots,
                    nt=nt,
                    sample_config=config_values,
                )
                outputs.append(synth.unsqueeze(0))
            return torch.cat(outputs, dim=0)

        if model.ndim == 3 and model.shape[0] == 1:
            model = model.squeeze(0)
        config = _config_from_tensor(sample_config)
        model = model.to(self.device)
        velocity = model_to_velocity(model, config)
        nz, nx = velocity.shape[-2], velocity.shape[-1]
        shot_count = n_shots if n_shots is not None else int(round((14.5 - config.src_x_start) / config.src_x_step)) + 1
        time_samples = nt if nt is not None else 2000
        source_amplitudes, source_locations, receiver_locations = self._build_geometry(shot_count, time_samples, nx, nz, config)

        outputs = []
        for start in range(0, shot_count, self.shot_batch_size):
            end = min(start + self.shot_batch_size, shot_count)
            out = scalar(
                velocity,
                [config.dz, config.dx],
                dt=config.dt,
                source_amplitudes=source_amplitudes[start:end],
                source_locations=source_locations[start:end],
                receiver_locations=receiver_locations[start:end],
                pml_width=[config.pml_width] * 4,
                pml_freq=config.freq,
                accuracy=config.accuracy,
            )
            outputs.append(out[-1])
        return torch.cat(outputs, dim=0)

    def image_from_observed_data(
        self,
        observed_data: torch.Tensor,
        current_model: torch.Tensor,
        observed_is_processed: bool | torch.Tensor = False,
        sample_config: torch.Tensor | None = None,
    ) -> torch.Tensor:
        if observed_data.ndim == 4 and current_model.ndim == 4:
            images = []
            for batch_index in range(observed_data.shape[0]):
                if torch.is_tensor(observed_is_processed) and observed_is_processed.ndim > 0:
                    processed_flag: bool | torch.Tensor = observed_is_processed[batch_index]
                else:
                    processed_flag = observed_is_processed
                config_values = sample_config[batch_index] if sample_config is not None and sample_config.ndim > 1 else sample_config
                image = self.image_from_observed_data(
                    observed_data[batch_index],
                    current_model[batch_index],
                    observed_is_processed=processed_flag,
                    sample_config=config_values,
                )
                images.append(image.unsqueeze(0))
            return torch.cat(images, dim=0)

        if torch.is_tensor(observed_is_processed):
            observed_is_processed_bool = bool(observed_is_processed.item())
        else:
            observed_is_processed_bool = bool(observed_is_processed)

        observed, model = self._ensure_single_sample(observed_data, current_model)
        config = _config_from_tensor(sample_config)
        velocity = model_to_velocity(model, config)
        n_shots, _n_receivers, nt = observed.shape
        nz, nx = velocity.shape[-2], velocity.shape[-1]
        source_amplitudes, source_locations, receiver_locations = self._build_geometry(n_shots, nt, nx, nz, config)

        with torch.no_grad():
            if observed_is_processed_bool:
                observed_scattered = observed
            else:
                direct_wave = estimate_direct_wave_batched(
                    velocity.detach(),
                    source_amplitudes,
                    source_locations,
                    receiver_locations,
                    config,
                    self.shot_batch_size,
                )
                observed_scattered = observed - direct_wave

        image = compute_rtm_illumination_compensated_batched(
            velocity=velocity,
            observed_scattered=observed_scattered,
            source_amplitudes=source_amplitudes,
            source_locations=source_locations,
            receiver_locations=receiver_locations,
            config=config,
            shot_batch_size=self.shot_batch_size,
            illumination_floor_fraction=self.illumination_floor_fraction,
            illumination_quantile=self.illumination_quantile,
        )
        del observed_scattered, source_amplitudes, source_locations, receiver_locations
        if self.device.type == "cuda":
            torch.cuda.empty_cache()
        return image.unsqueeze(0)

    def forward(
        self,
        observed_bscan: torch.Tensor,
        model: torch.Tensor,
        observed_is_processed: bool | torch.Tensor = False,
        sample_config: torch.Tensor | None = None,
    ) -> torch.Tensor:
        return self.image_from_observed_data(
            observed_bscan,
            model,
            observed_is_processed=observed_is_processed,
            sample_config=sample_config,
        )
